#define DOOM_IMPLEMENTATION
#include "PureDOOM.h"
#include "io.h"
#include "memory_management.h"
#include "string.h"
#include "vga.h"
#include <stdint.h>

// WAD symbols generated by objcopy
extern const uint8_t _binary___bin_doom1_wad_start[];
extern const uint8_t _binary___bin_doom1_wad_end[];
extern const uint8_t _binary___bin_doom1_wad_size[];

static int doom_wad_offset = 0;

void my_doom_print(const char* str) {
    print(str);
}

void* my_doom_malloc(int size) {
    void* ptr = malloc(size);
    if (ptr) {
        memset(ptr, 0, size);
    }
    return ptr;
}

void my_doom_free(void* ptr) {
    free(ptr);
}

static int is_wad(const char* name) {
    int len = strlen(name);
    if (len >= 9) {
        const char* end = name + len - 9;
        if (strcmp(end, "doom1.wad") == 0 || strcmp(end, "DOOM1.WAD") == 0) return 1;
    }
    return 0;
}

void* my_doom_open_file(const char* filename, const char* mode) {
    (void)mode;
    if (is_wad(filename)) {
        doom_wad_offset = 0;
        return (void*)1; // Return dummy handle for WAD
    }
    return NULL; // Return NULL for config files or other WADs
}

void my_doom_close_file(void* handle) {
    (void)handle;
}

int my_doom_read_file(void* handle, void* buf, int count) {
    (void)handle;
    uint32_t wad_size = _binary___bin_doom1_wad_end - _binary___bin_doom1_wad_start;
    if (doom_wad_offset + count > wad_size) {
        count = wad_size - doom_wad_offset;
    }
    if (count <= 0) return 0;
    
    memcpy(buf, &_binary___bin_doom1_wad_start[doom_wad_offset], count);
    doom_wad_offset += count;
    return count;
}

int my_doom_write_file(void* handle, const void* buf, int count) {
    (void)handle; (void)buf;
    return count;
}

int my_doom_seek_file(void* handle, int offset, doom_seek_t origin) {
    (void)handle;
    uint32_t wad_size = _binary___bin_doom1_wad_end - _binary___bin_doom1_wad_start;
    if (origin == DOOM_SEEK_SET) {
        doom_wad_offset = offset;
    } else if (origin == DOOM_SEEK_CUR) {
        doom_wad_offset += offset;
    } else if (origin == DOOM_SEEK_END) {
        doom_wad_offset = wad_size + offset;
    }
    if (doom_wad_offset < 0) doom_wad_offset = 0;
    if (doom_wad_offset > wad_size) doom_wad_offset = wad_size;
    return 0;
}

int my_doom_tell_file(void* handle) {
    (void)handle;
    return doom_wad_offset;
}

int my_doom_eof_file(void* handle) {
    (void)handle;
    uint32_t wad_size = _binary___bin_doom1_wad_end - _binary___bin_doom1_wad_start;
    return doom_wad_offset >= wad_size;
}

static inline uint64_t read_tsc() {
    uint32_t lo, hi;
    __asm__ volatile ("rdtsc" : "=a" (lo), "=d" (hi));
    return ((uint64_t)hi << 32) | lo;
}

void my_doom_gettime(int* sec, int* usec) {
    // Shift TSC right by 20 to fit into 32-bit and avoid 64-bit division errors.
    // 1 GHz / 2^20 is approximately 953 ticks per second.
    uint32_t tsc_shifted = (uint32_t)(read_tsc() >> 20);
    uint32_t tps = 953;
    
    *sec = tsc_shifted / tps;
    *usec = ((tsc_shifted % tps) * 1000000) / tps;
}

char* my_doom_getenv(const char* var) {
    if (strcmp(var, "HOME") == 0) return "/";
    if (strcmp(var, "DOOMWADDIR") == 0) return "/";
    return 0;
}

void my_doom_exit(int code) {
    vga_set_text_mode();
    print("DOOM Exited with code: ");
    print_int(code);
    print("\n");
    while(1);
}

static doom_key_t translate_key(uint8_t scancode) {
    // Basic translations for testing, assumes PS/2 scan codes
    switch(scancode) {
        case 0x11: return DOOM_KEY_UP_ARROW; // W mapping for up
        case 0x1E: return DOOM_KEY_LEFT_ARROW; // A
        case 0x1F: return DOOM_KEY_DOWN_ARROW; // S
        case 0x20: return DOOM_KEY_RIGHT_ARROW; // D
        case 0x1D: return DOOM_KEY_CTRL; // Fire
        case 0x39: return DOOM_KEY_SPACE; // Open door
        case 0x01: return DOOM_KEY_ESCAPE;
        case 0x1C: return DOOM_KEY_ENTER;
        default: return DOOM_KEY_UNKNOWN;
    }
}

void run_doom() {
    vga_set_mode_32bpp();
    
    // PureDOOM functions
    doom_set_print(my_doom_print);
    doom_set_malloc(my_doom_malloc, my_doom_free);
    doom_set_getenv(my_doom_getenv);
    doom_set_file_io(my_doom_open_file, my_doom_close_file, my_doom_read_file, my_doom_write_file, my_doom_seek_file, my_doom_tell_file, my_doom_eof_file);
    doom_set_gettime(my_doom_gettime);
    doom_set_exit(my_doom_exit);
    
    // Set 320x200 software rendering
    doom_set_resolution(320, 200);
    
    // Setup WAD paths (dummy since we intercept file IO)
    int argc = 1;
    char* argv[] = {"doom"};
    doom_init(argc, argv, 0);
    
    // Clear screen to black (32bpp means 4 bytes per pixel)
    uint32_t* fb = (uint32_t*)vga_get_framebuffer();
    for (int i = 0; i < 800 * 600; i++) fb[i] = 0;
    
    uint8_t scancode;
    int dx, dy, btn;
    
    while (1) {
        doom_update();
        
        // Input poll
        if (input_poll(&scancode, &dx, &dy, &btn) == INPUT_KEYBOARD) {
            bool release = scancode & 0x80;
            scancode &= 0x7F;
            doom_key_t key = translate_key(scancode);
            if (key != DOOM_KEY_UNKNOWN) {
                if (release) {
                    doom_key_up(key);
                } else {
                    doom_key_down(key);
                }
            }
        }
        
        // Render 
        const uint8_t* doom_fb = doom_get_framebuffer(4); // 4 = RGBA
        
        for (int y = 0; y < 200; y++) {
            for (int x = 0; x < 320; x++) {
                uint32_t pixel = ((uint32_t*)doom_fb)[y * 320 + x];
                uint8_t r = pixel & 0xFF;
                uint8_t g = (pixel >> 8) & 0xFF;
                uint8_t b = (pixel >> 16) & 0xFF;
                
                // Construct 32bpp pixel (0x00RRGGBB)
                uint32_t vga_pixel = (r << 16) | (g << 8) | b;
                
                // Scale 2x and center
                int draw_x = 80 + (x * 2);
                int draw_y = 100 + (y * 2);
                fb[draw_y * 800 + draw_x] = vga_pixel;
                fb[draw_y * 800 + draw_x + 1] = vga_pixel;
                fb[(draw_y + 1) * 800 + draw_x] = vga_pixel;
                fb[(draw_y + 1) * 800 + draw_x + 1] = vga_pixel;
            }
        }
    }
}
